filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log  # Você pode ajustar este caminho conforme necessário

output.elasticsearch:
  hosts: ["http://opensearch-node:9200"]  # Certifique-se de que o hostname está correto
  username: "admin"
  password: "SuaSenhaForte123!"
